apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-b
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx-b
  template:
    metadata:
      labels:
        app: nginx-b
        ppgcomp.unioeste.br/price: "le-0.15"
      annotations:
        lfaltran.io/deployment.node.log: "true"        
    spec:
      # schedulerName: label-affinity-scheduler
      containers:
      - name: nginx-b
        image: nginx:99999
        imagePullPolicy: IfNotPresent
        resources:
          requests:
              cpu: "200m"
              memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort: 8080