apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-e
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx-e
  template:
    metadata:
      labels:
        app: nginx-e
        ppgcomp.unioeste.br/cloud_vendor: "eq-gcp"
        ppgcomp.unioeste.br/dc_continent: "eq-america"
        ppgcomp.unioeste.br/price: "le-0.10"
      annotations:
        lfaltran.io/deployment.node.log: "true"
    spec:
      schedulerName: label-affinity-scheduler
      containers:
      - name: nginx-d
        image: nginx:99999
        imagePullPolicy: IfNotPresent
        resources:
          requests:
              cpu: "200m"
              memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort: 8080