apiVersion: apps/v1
kind: Deployment
metadata:
  name: boinc-f
spec:
  replicas: 0
  selector:
    matchLabels:
      app: boinc-f
  template:
    metadata:
      labels:
        app: boinc-f
        ppgcomp.unioeste.br/green_energy_perc: "gt-0"
      annotations:
        lfaltran.io/deployment.node.log: "true"
    spec:
      schedulerName: label-affinity-scheduler
      containers:
      - name: boinc-f
        image: zilman/boinc:99999
        imagePullPolicy: IfNotPresent
        resources:
          requests:
              cpu: "200m"
              memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort: 8080