apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-g
spec:
  replicas: 0
  selector:
    matchLabels:
      app: app-g
  template:
    metadata:
      labels:
        app: app-g
        ppgcomp.unioeste.br/cloud_vendor: "in-azure-aws-gcp-oracle"
        ppgcomp.unioeste.br/os_type: "in-linux-windows"
        ppgcomp.unioeste.br/app_environment: "notin-tst"
      annotations:
        lfaltran.io/deployment.node.log: "true"
    spec:
      schedulerName: label-affinity-scheduler
      containers:
      - name: app-g
        image: hendrikmaus/kubernetes-dummy-image:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "25m"
            memory: "16Mi"