admin_password: admin
rancher_version: v2.3.5
ROS_version: 1.5.1
# Empty defaults to latest non-experimental available
k8s_version: "v1.17.4-rancher1-2"
cluster_name: "ppgcomp"
server:
  cpus: 1
  memory: 1536
node:
  count: 6
  cpus: 1
  memory: 1536
ip:
  master: 172.22.101.100
  server: 172.22.101.101
  node:   172.22.101.111
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: private_network
