apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: las-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: kube-metrics
rules:
- apiGroups:
    - metrics.k8s.io
  resources:
    - pods
    - nodes
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: kube-deployments
rules:
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: las-listener
subjects:
- kind: ServiceAccount
  namespace: default
  name: las-service-account
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: las-metrics
subjects:
- kind: ServiceAccount
  namespace: default
  name: las-service-account
roleRef:
  kind: ClusterRole
  name: kube-metrics
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: las-deployments
subjects:
- kind: ServiceAccount
  namespace: default
  name: las-service-account
roleRef:
  kind: ClusterRole
  name: kube-deployments
  apiGroup: rbac.authorization.k8s.io