apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-affinity-scheduler
  labels:
    app: label-affinity-scheduler
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-affinity-scheduler
  template:
    metadata:
      labels:
        app: label-affinity-scheduler
    spec:
      serviceAccount: las-service-account
      containers:
        - name: label-affinity-scheduler
          image: lfaltran/label-affinity-scheduler:1.3
          args: ["label-affinity-scheduler", "ppgcomp.unioeste.br", "true"]
          imagePullPolicy: Always