apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        lfaltran.io/deployment.node.log: "true"
    spec:
      schedulerName: label-affinity-scheduler
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "8m"
            memory: "16Mi"